name: pimnet
channels:
  - pytorch
dependencies:
  - cudatoolkit=11.3
  - matplotlib
  - pip
  - python=3.9
  - pytorch::pytorch=1.10.0
  - pytorch::torchvision=0.11.0
  - scikit-image
  - scipy
  - tqdm
  - pip:
    - opencv-python