name: retinaface
channels:
  - nvidia
  - pytorch
dependencies:
  - matplotlib
  - nvidia::cudatoolkit=11.1
  - pip
  - python=3.9
  - pytorch::pytorch=1.9.0
  - pytorch::torchvision=0.10.0
  - tqdm
  - scipy
  - pip:
    - opencv-python