name: retinaface
channels:
  - pytorch
dependencies:
  - cudatoolkit=11.3
  - matplotlib
  - pip
  - python=3.9
  - pytorch::pytorch=1.10.1
  - pytorch::torchvision
  - scipy
  - tqdm
  - pip:
    - opencv-python-headless